# -*- coding: utf-8 -*-
"""Alura_Imersão_de_Dados_Primeira_Aula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tYCUdYCAcdXFVSEf3ZZMzyebnATthD-p
"""

import pandas as pd
url = "https://gist.githubusercontent.com/tgcsantos/3bdb29eba6ce391e90df2b72205ba891/raw/22fa920e80c9fa209a9fccc8b52d74cc95d1599b/dados_imoveis.csv"
dados = pd.read_csv(url)
dados.head(10)
# como importar a biblioteca pandas e em seguida a base de dados do gihub

dados.sample(10)
# uma amostra dos dados importados de acordo com o numero colocado dentro do parenteses

dados.info()
# traz informações sobre o dataframe importado

dados.Metragem.mean()
# média de metragem

dados["Metragem"].mean()
# Outra forma de pegar a média de metragem

dados["Bairro"] == "Vila Mariana"))
# Mostra o número de Bairros que são Vila Mariana

tem_imoveis_vila_mariana = (dados["Bairro"] == "Vila Mariana")
dados[tem_imoveis_vila_mariana]
# Seleciona somente as linhas que contém Vila Mariana

imoveis_vila_mariana = dados[tem_imoveis_vila_mariana]
imoveis_vila_mariana["Metragem"].mean()
# Calcula a média da Metragem das linhas que contem o Bairro Vila Mariana

dados["Bairro"].value_counts()
# Conta quantos itens cada bairro possui

n_imoveis_bairro = dados["Bairro"].value_counts()
# Cria uma variavel contendo quantos itens possui em cada Bairro
n_imoveis_bairro.head(10).plot.bar()
# traz um gráfico de barras com os 10 Bairros com maior número de imóveis

"""Desafios:

1 - Realizar a média da metragem para cara um dos bairros (Paulo)

2 - 2 formas de selecionar os dados por bairro (consultar os métodos na documentação do pandas) (Thiago)

3 - Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF, tentar colocar alguma conclusão (Thiago)

4 - Pegar outros estatísticas dos dados, média, mediana, mim, max (Vivi)

5 - Descobrir quais são os bairros que não tem nome de Rua. (Vivi)

# **1 - Realizar a média da metragem para cara um dos bairros (Paulo)**
"""

dados.groupby("Bairro").mean()["Metragem"]
# Agrupando as linhas de cada Bairro e tirando a média de cada um

"""# **2 - Formas de selecionar os dados por bairro (consultar os métodos na documentação do pandas) (Thiago)**"""

dados[dados['Bairro'] == "Santana"]
# Uma forma de selecionar os bairros Santana

dados.query('Bairro == "Pirituba"')
# Uma outra forma de selecionar os bairros Pirituba

"""# **3 - Explorar alguns gráficos na documentação e aplicar nas demais colunas do DF, tentar colocar alguma conclusão (Thiago)**"""

quartos_sp = dados["Quartos"].value_counts()
quartos_sp.plot.bar()
# A maioria dos Bairros possuem 3 Quartos

med_quartos_bairro = dados.groupby("Bairro").mean()["Quartos"]
# Criando uma variável onde é agrupado as linhas de cada Bairro e tirando a média de Quartos cada um
med_quartos_bairro.head(10).plot.pie()
# Alto da Boa Vista é o Bairro tem a maior média de Quartos das 10 primeiras linhas

"""# **4 - Pegar outros estatísticas dos dados, média, mediana, mim, max (Vivi)**"""

dados.describe()

"""# **5 - Descobrir quais são os bairros que não tem nome de Rua. (Vivi)**"""

bairros_sem_rua = dados[(dados["Rua"].isnull())]
bairros_sem_rua["Bairro"].value_counts()